name: Download Packages
on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Pip Download
        run: |
          mkdir python_pkgs
          python -m pip install --upgrade pip
          pip download "crewai[tools]==1.14.1" litellm==1.83.0 -d python_pkgs

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: crewai-310-packages
          path: python_pkgs/
